image: openjdk:8

variables:
   GIT_STRATEGY: clone
   SSL_SELF_SIGNED: "true"
   PROJECTNAME: "ImageScaler"

before_script:
  - java -version

stages:
  - javadoc
  - compile

verify:
  allow_failure: true
  script:
    - wget ${SERVER}ci/javadoc.sh
    - chmod 755 javadoc.sh
    - ./javadoc.sh
  stage: javadoc

javadoc:
  script:
    - cd ${PROJECTNAME}
    - find src -name "*.java" > sources.txt
    - javadoc -private @sources.txt
  stage: javadoc

compile:
  script:
    - chmod -R 777 ./*
    - cd ${PROJECTNAME}
    - ls -l
    - rm -rf ./bin
    - mkdir bin
    - find src -name "*.java" > sources.txt
    - find lib -name "*.jar" > libs.txt
    - libs=""
    - while read line; do libs=$libs./$line:; done <libs.txt
    - libs=$libs.
    - javac -cp $libs -d ./bin -g -verbose -version -encoding "UTF-8" @sources.txt
  stage: compile
  environment: builds
